ray-x/lsp_signature.nvim

lua/lsp_signature.lua

Fix the https://github.com/ray-x/lsp_signature.nvim/issues/4
Please check it out.
Thank you.

fix: match_parameter function when result's parameter is nil.

---

lua/lsp_signature_helper.lua

Maybe it's pyright issue.
lsp_signature.nvim should cover some cases.
Please check it out.
Thank you.

fix: helper.match_parameter function when nextParameter is nil.

---

README.md
lua/lsp_signature.lua

Omnsiharp-roslyn has useless characters set as the trigger characters
for signature help, namely `.`, `?` and `[` (see this issue for more
info: https://github.com/OmniSharp/omnisharp-roslyn/issues/1119).
I added the `extra_trigger_chars` option so I could set '(' and ','
as additional triggers when using omnisharp, and I figured these
modifications could be useful for other servers as well.

Added `extra_trigger_chars` setting

---

README.md
lua/lsp_signature.lua

Sometimes, when the signature is triggered by mistake outside of functions, I was getting some errors because the `lines` variable is `nil`. These checks seem to make the errors go away.

Fixed errors shown when `lines` is nil

---

lua/lsp_signature_helper.lua

All the magic characters were escaped using the `%*` sequence which resulted in missing parameter highlighting.

fix: use proper escape sequence for each magic character

---

lua/lsp_signature.lua

Hi! Sorry to bother you again. I would like to use this plugin without border (using setting 'none'), but it's quite hard to see sometimes. I could use a different highlight, but I like the signature to not be too distracting. I like how jedi-vim adds a single character padding left and right:
I've tried adding pad_left/pad_right to the config dictionary of the `open_floating_preview`, but I couldn't get it to show up. So now I've added 'spaces' to the lines. It works for me, but I guess it would be nice to have a configurable option? I'm not sure how to add that, I don't have a lot of experience in lua.
Before:
After:

Enhancement: add padding around signature when border is none

---

README.md
lua/lsp_signature.lua

This allows specifying `toggle_key` in `on_attach`, and only maps `toggle_key` in buffers where LSP is attached.

Map toggle_key in on_attach() instead of setup()

---

lua/lsp_signature.lua
lua/lsp_signature_helper.lua

Hi,
These are quite some significant changes to make the signature help pop-up more reliably. Also improves the positioning of the signature help.
Improvements:
- When entering insert mode always show signature help when available
- When possible, request the signature at the nearest trigger character, this improves reliability. For example, when entering insert mode inside a function call, but not next to a trigger character, the signature will now be shown.
- Make the LSP responsible to close the signature help (thus when none are returned and fix_pos==true)
- When the LSP returns `<function_name>(...)` also use `function_name` to position the signature help more correctly. This is useful if there are more signatures on a single line.
Most of these improvements have only been tested …

Improvements to signature help (especially when fix_pos=true)

---

lua/lsp_signature.lua

Unfortunately, LuaJIT supports Lua 5.1 with a slightly random set of Lua 5.2 extensions, which means it's possible to write code which doesn't work on those platforms where only Lua 5.1 (and not LuaJIT) can be used (e.g. OpenBSD).
In this case "goto ::x::" isn't a Lua 5.1 feature. Fortunately the change in control flow in this case is easy and, in my opinion, fairly natural.

Lua 5.1 doesn't support goto labels.

---

lua/lsp_signature.lua

This is where virtual text hint is shown before #105. What's more, using `overlay` can make the code around hard to see.

Show virtual text hint after eol; Correctly calculate display width

---

lua/lsp_signature/init.lua

when there is a no parameter signature, it's be filtered by mistake.
clangd 11.0
int a();
int a(int x);
int a(int x, int y);
int main() {
a( // only show a(int x) and a(int x, int y)
}

fix bugs that not show no parameter function signature.

---

README.md

Replace `recommanded` with `recommended`

Fix typo: recommended

---

lua/lsp_signature/init.lua

Initially created this as an issue but as I dug deeper, I thought I could fix it instead.
---- Issue
Did a couple of test with this. 
1. I change the filetype from my multi-filetype to just plain haxe, and everything works.
2. Removing the comment from the function definition, also fixes it.
Turns out if the file type is recognized, i.e. just haxe, the first line will not be render, but because I use a multi-filetype for my files, the rendering of the first line breaks the highlighter.
----
Solutions
Initially I investigated whether I can continue to show the filetype, but instead figure out which line to highlight. After  digging the code base for an hour or so, I couldn't find a good way to handle it without making the code really messy.
I also realised that the function `ft2md` seems …

use only the first filetype when it is a multi-filetype

---

lua/lsp_signature/init.lua

Sorry for the previous commit as I am not familiar with lua's string api, and I am not sure how the previous case works for me.
This should really split the filetype properly

fix multi-filetype not splitting properly

---

lua/lsp_signature/helper.lua

Some language servers return an invalid `activeParameter` value (robotframework_ls) for example. This PR handle gracefully those errors.

Fix handling of invalid active parameters

---

README.md

Using the current default cfg in README introduces this.

fix default cfg

---

lua/lsp_signature/init.lua
tests/signature_spec.lua

Language servers can be slow to respond to the
`textDocument/signatureHelp` request. During that time, the user could have moved to another buffer. The signature would be shown for the current buffer even though it was meant for some other buffer.
In this reproduction, I modify some code to make `tsserver` busy, quickly ask for `signatureHelp` and then quickly open Telescope:
https://user-images.githubusercontent.com/889383/202849435-e4ec105f-3b2f-4573-b0cd-a56decb43947.mp4
Let's only show the signature if it is for the current buffer.
The same Telescope bug reproduction with the fix from this PR (it no longer causes an error because the signature is ignored):
https://user-images.githubusercontent.com/889383/202849512-c1595d6d-9c55-4f2f-8b76-bef5781bc9d7.mp4
This bugfix is cherry-picked …

ignore signature results for other buffers

---

lua/lsp_signature/init.lua

This error was annoying me very much
```
Error executing vim.schedule lua callback: vim/_init_packages.lua:0: ...cker/start/lsp_signature.nvim/lua/lsp_signature/init.l
ua:110: '=' expected near 'if'
stack traceback:
[C]: in function 'error'
vim/_init_packages.lua: in function <vim/_init_packages.lua:0>
```

Fix breaking typo

---

lua/lsp_signature/init.lua

when current line is the first line of current window(lines_above = 0), the value of show_at is still cur_line - 1, it should be changed to cur_line. and new code is compatible with the old code which is when current line is the first line of buffer, show_at = 0. #241

Fix virtual text doesn't show

---

lua/lsp_signature/helper.lua

In case we are on top two lines and the signature help is triggered we do not want to show the signature on current line and overlap it.

helper: forbid the overlap on top lines

---

lua/lsp_signature/init.lua

Hi, thanks for the plugin!
May I have the value of `woff` passed to `floating_window_off_x` function?
I want to position the floating window at an absolute position (such that it anchors to the colorcolumn), but since the code adds whatever value `woff` to the output value, it is really hard to accomplish.
With the `woff` value passed to the function, I will be able to do something like this to place the window at the exact position I want.
```lua
floating_window_off_x = function(info)
local woff = info.woff
local the_absolute_position_i_want = 100
local cur_pos = vim.api.nvim_win_get_cursor(0)[2] + 1
return the_absolute_position_i_want - woff - cur_pos
end
```
BTW, what does `woff` stand for? _Width of function_? _Word offset_?
Thanks in advance,
pysan3

feat (config): pass woff to `floating_window_off_x` function

---

lua/lsp_signature/helper.lua

This pr fixes the following error on nightly.
```
Error executing vim.schedule lua callback: ...pack/opt/lsp_signature.nvim/lua/lsp_signature/helper.lua:393: attempt to call field '_trim' (a nil value)
stack traceback:
...pack/opt/lsp_signature.nvim/lua/lsp_signature/helper.lua:393: in function 'cal_pos'
...ptpack/opt/lsp_signature.nvim/lua/lsp_signature/init.lua:501: in function 'handler'
/home/notomo/.local/nvim/share/nvim/runtime/lua/vim/lsp.lua:1505: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```
📝
- `vim.lsp.util._trim` is not public function. `_trim` is removed on nightly.
- vim.split trimempty option is implemented from v.0.6.0: https://github.com/neovim/neovim/releases/tag/v0.6.0

fix: attempt to call field '_trim' (a nil value) error

---

lua/lsp_signature/helper.lua

actually last PR(#243 )didn't solve the issue(#242 ) because the calculation should be done before make_floating_popup_options()

Fix incorrect floating window position

---

lua/lsp_signature/helper.lua

perf: reduce `cmp.visible()` timeout from 1000ms to 42ms

---

lua/lsp_signature/helper.lua

Under Neovim 0.9.4, the `lsp_signature` plugin encountered a critical error when typing parameters inside a function, resulting in the following error:
```plaintext
Error executing vim.schedule lua callback: ...vim/lazy/lsp_signature.nvim/lua/lsp_signature/helper.lua:677: Cursor position outside buffer
stack traceback:
[C]: in function 'nvim_win_set_cursor'
...vim/lazy/lsp_signature.nvim/lua/lsp_signature/helper.lua:677: in function 'highlight_parameter'
.../nvim/lazy/lsp_signature.nvim/lua/lsp_signature/init.lua:618: in function 'handler'
...bob/v0.9.4/nvim-macos/share/nvim/runtime/lua/vim/lsp.lua:1393: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```
- Addressed the cursor position error during parameter input inside a function in the `lsp_signature` plugin.
- Wrapped …

fix: cursor position outside buffer error

---

lua/lsp_signature/helper.lua
lua/lsp_signature/init.lua

Fixes https://github.com/ray-x/lsp_signature.nvim/issues/311
See https://neovim.io/doc/user/news.html

fix: Use get_active_clients if Neovim <0.10

---

lua/lsp_signature/helper.lua

I know PR #312 was made to try and address this issue. But this error is still popping up for me on the latest prerelease version of Neovim (NVIM v0.10.0-dev-2539+ga69c72063 at the moment) with the macos build. With this PR, I intend to fix this issue by checking if the method "vim.lsp.get_clients" exists before running it, and if not then run "vim.lsp.get_active_clients".

fix: "Attempt to call field 'get_clients' (a nil value)" error for some 0.10 versions

---

lua/lsp_signature/helper.lua

This PR will fix the following deprecated warning.
```
vim.lsp.util.try_trim_markdown_code_blocks() is deprecated, use nil instead. :help deprecated
Feature will be removed in Nvim 0.12
stack traceback:
...tomo/.local/nvim/share/nvim/runtime/lua/vim/lsp/util.lua:1880: in function 'try_trim_markdown_code_blocks'
...pack/opt/lsp_signature.nvim/lua/lsp_signature/helper.lua:418: in function 'cal_pos'
...ptpack/opt/lsp_signature.nvim/lua/lsp_signature/init.lua:502: in function 'handler'
...mo/.local/nvim/share/nvim/runtime/lua/vim/lsp/client.lua:685: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```

fix: remove use of `vim.lsp.util.try_trim_markdown_code_blocks()`

---

lua/lsp_signature/init.lua

Hi there, best plugins!
The `on_attach` function will execute when the corresponding buffer is created If a file already bound to LSP. While preserving the original behavior, creating a new augroup will remove the previously loaded events (by default). This will result in the inability to use all the features of lsp_signature.nvim in the previous buffer. Sincerely hope this issue gets resolved promptly.
https://github.com/ray-x/lsp_signature.nvim/assets/38415769/3b29229f-8a6b-47cc-a307-ebb06c4376fe
Regards!

fix: loaded events should not be deleted when the augroup exists.

---

README.md
doc/lsp_signature.txt
lua/lsp_signature/init.lua

This PR aims to add support for 3 separate icons to be used for the hint_prefix, based on where the hint is displayed:
- 'above' the current line
- 'current' line
- 'below' the current line
When a string is given as the option to 'hint_prefix', it's assumed to be the only icon used.
screenshots:

[feat]: multiple hint_prefix icons, based on hint's location

---

lua/lsp_signature/init.lua

Hello @ray-x,
I come from [Issue #298](https://github.com/ray-x/lsp_signature.nvim/issues/298). I encountered a problem while trying to apply the solution suggested in this issue. Specifically, I found that the configuration option `cursorhold_update = false` does not work as expected. The root cause appears to be that the `autocmd` is defined before the user's configuration is applied, resulting in the default settings being used.
Please review the changes and provide feedback. Additionally, it would be great if you could take a look at Issue #298 to confirm if there might be other underlying issues.

Fix cursorhold_update Configuration Handling in lsp_signature.nvim

---

lua/lsp_signature/init.lua

when using a hlgroup that has a background, and when using only virtual text with no floating window text like this:
```lua
floating_window = false,
hint_scheme = "Todo",
```
The resulting virtual text adds the background color to the virtual text. This PR fixes the issue by not assigning a highlighting group to the padding
---
before:
after:

fix: virtual text with a hlgroup with background

---

README.md
lua/lsp_signature/helper.lua

This is a small patch. The `.lhs` and `.rhs` properties do not exist (any longer?; old api?). I have gotten errors trying to set custom keymaps.
This is written in the example config;
```lua
keymaps = { "j", "<C-o>j" },
```
But this seems to provoke the following error:
I pressume setting it in the following way was intended:
```lua
keymaps = { { "j", "<C-o>j" }, { "k", "<C-o>k" }, },
```
It raises a similar error.
Using indexes to instead get the keymap table values resolves the issue and I presume does what was intended.

fix: keymaps config helper

---

lua/lsp_signature/helper.lua
lua/lsp_signature/init.lua

vim.lsp.util.make_position_params requires the explicit client encoding as of nvim v0.11
Fixes: https://github.com/ray-x/lsp_signature.nvim/issues/346

fix: make_position_params needs offset encoding in v0.11

---

lua/lsp_signature/init.lua

`vim.lsp.get_client_by_id` was being called twice, the first time using a client `id`, and the second time using the `vim.lsp.Client` returned from the first call.
Fixing this fixes #354

fix: not working on neovim 0.11

---

lua/lsp_signature/helper.lua

This fix deals with an annoyance that the hint wasn't appearing when using the Roslyn lsp.
This is what the LSP sends to neovim:
```
{ "signatures" =  { "documentation" = { "kind" = "plaintext", "value" = "the center of a circle"}, "label" = "center"}
```
This is how it was being rendered before the change:
This is how it is being rendered after the change:
I have tested with the lua_ls, omnisharp and Roslyn, everything seems to be working fine

Fixing the hint to show when using the roslyn lsp

---

lua/lsp_signature/init.lua

I periodically started getting errors from tsserver, as shown in the screenshot. After some debugging, I found that an error occurs when the cursor is on an empty line(with line feed only) and the character number in the query is 1, although it should be 0 as far as I understand. After this correction, the errors disappeared.

fix: incorrect calculation of character index

---

lua/lsp_signature/init.lua

The official documentation says that the `hint_inline` function should return 'eol' to place the hint at the end of the line or 'right_align' to align the hint to the right of the line. However, even if the function returns 'eol' or 'right_align', the hint will always be inline
Is this the desired behavior?

fix: `hint_inline` treats 'eol' and 'right_align' as 'inline'

---

lua/lsp_signature/init.lua

The lsp_signature displays hint in the same line also if specify function which will return false to disable inline hint.
`_LSP_SIG_CFG.hint_inline` is function and it is evaluated as truthy value.
```lua
opts = {
hint_inline = function() return false end,  -- default
hint_prefix = {
above = "↙ ",
current = "←  ",
below = "↖ "
},
}
```

Fix handling false which is returned by hint_inline function

---

lua/lsp_signature/init.lua

Currently, the LspAttach autocmd keeps overwriting my custom `LspSignatureActiveParameter` highlight. This PR fixes it by checking for its existence before setting it

fix: check if highlight exists before overwriting
